# -*- coding: utf-8 -*-
"""朋友版儀表板.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_RUSdinJarfhNaJozQGa3zB58rsFka14
"""

# app.py - MJ 指標看盤工具（朋友版）
# 部署方式：上傳到 Streamlit Cloud 即可使用

import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime, timedelta

# ============================================================
# 頁面設定
# ============================================================
st.set_page_config(
    page_title="MJ 指標看盤工具",
    page_icon="📊",
    layout="wide"
)

# 純黑風格 CSS
st.markdown("""
<style>
    .stApp {
        background-color: #000000;
    }
    .stSelectbox, .stTextInput, .stButton {
        background-color: #121212;
    }
    .stSelectbox > div, .stTextInput > div {
        background-color: #121212 !important;
        color: #e0e0e0 !important;
    }
    .stSelectbox label, .stTextInput label {
        color: #9ca3af !important;
    }
    .stButton button {
        background-color: #2962ff !important;
        color: #ffffff !important;
        font-weight: bold !important;
        border: none !important;
        border-radius: 6px !important;
    }
    .stButton button:hover {
        background-color: #1a4fcc !important;
    }
    .stMarkdown h1, .stMarkdown h2, .stMarkdown h3 {
        color: #ffffff !important;
    }
    .stMarkdown p {
        color: #e0e0e0 !important;
    }
    div[data-testid="stExpander"] {
        background-color: #121212 !important;
        border: 1px solid #2d2d2d !important;
        border-radius: 8px !important;
    }
</style>
""", unsafe_allow_html=True)

# ============================================================
# 標題
# ============================================================
col_title, col_help = st.columns([10, 1])
with col_title:
    st.markdown("# 📊 MJ 指標看盤工具")
    st.markdown("輸入股票代號，即時顯示 MJ 買賣訊號")
with col_help:
    with st.popover("❓", use_container_width=True):
        st.markdown("""
        ### 📘 使用說明
        - **台股/美股**：輸入代號即可（如 `2330`、`AAPL`）
        - **上櫃台股**：輸入代號即可（如 `6488`）
        - **港股**：輸入代號後加 `.HK`（如 `0700.HK`）
        - **陸股**：輸入代號後加 `.SS` 或 `.SZ`（如 `600519.SS`）

        **市場下拉選單**：選擇對應市場，系統會自動補綴代號格式。

        **週期切換**：日線 / 週線 / 月線，MJ 標記都會顯示。

        **疊加指標**：可選擇 MA、布林、VWAP 疊加在主圖上。
        """)

# ============================================================
# 輸入區
# ============================================================
col1, col2, col3 = st.columns([3, 2, 1])

with col1:
    symbol_input = st.text_input(
        "股票代號",
        value="2330",
        placeholder="輸入代號 (如 2330, AAPL, 0700.HK)"
    )

with col2:
    market = st.selectbox(
        "市場",
        options=["台股", "美股", "港股", "陸股"],
        index=0
    )

with col3:
    st.write("")  # 垂直對齊
    st.write("")  # 垂直對齊
    query_btn = st.button("🔍 查詢", use_container_width=True)

# ============================================================
# 輔助函數：市場補綴
# ============================================================
def format_symbol(symbol, market):
    symbol = symbol.strip().upper()
    if market == "台股":
        if "." not in symbol:
            return symbol + ".TW"
        return symbol
    elif market == "港股":
        if "." not in symbol:
            return symbol + ".HK"
        return symbol
    elif market == "陸股":
        if "." not in symbol:
            return symbol + ".SS"
        return symbol
    else:  # 美股
        return symbol

# ============================================================
# MJ 指標計算（與主程式一致）
# ============================================================
def calculate_mj_indicators(df, j_period=21, fast=5, slow=34, signal=5):
    df = df.copy()
    if len(df) < 30:
        return None

    # 計算 J 線
    low_n = df['Low'].rolling(window=j_period).min()
    high_n = df['High'].rolling(window=j_period).max()
    denom = high_n - low_n
    denom = denom.replace(0, np.nan)
    rsv = (df['Close'] - low_n) / denom * 100
    rsv = rsv.fillna(50)

    k_list, d_list = [50.0], [50.0]
    for r in rsv.values[1:]:
        k = (2/3) * k_list[-1] + (1/3) * r
        d = (2/3) * d_list[-1] + (1/3) * k
        k_list.append(k)
        d_list.append(d)

    df['K'] = k_list
    df['D'] = d_list
    df['J'] = 3 * df['K'] - 2 * df['D']

    # 計算 MACD 柱狀體
    ema_fast = df['Close'].ewm(span=fast, adjust=False).mean()
    ema_slow = df['Close'].ewm(span=slow, adjust=False).mean()
    df['DIF'] = ema_fast - ema_slow
    df['MACD_Signal'] = df['DIF'].ewm(span=signal, adjust=False).mean()
    df['Hist'] = (df['DIF'] - df['MACD_Signal']) * 2

    return df

# ============================================================
# 輔助函數：重採樣
# ============================================================
def resample_kline(df, rule='W-FRI'):
    resampled = df.resample(rule).agg({
        'Open': 'first', 'High': 'max', 'Low': 'min', 'Close': 'last', 'Volume': 'sum'
    }).dropna(subset=['Close'])
    return resampled

# ============================================================
# 輔助函數：計算 MA、布林、VWAP
# ============================================================
def calc_sma(data, window):
    if len(data) < window:
        return [None] * len(data)
    res = []
    for i in range(len(data)):
        if i < window - 1:
            res.append(None)
        else:
            res.append(sum(data[i-window+1:i+1]) / window)
    return res

def calc_bollinger(closes, n=20, k=2):
    mid = calc_sma(closes, n)
    upper, lower = [], []
    for i in range(len(closes)):
        if i < n - 1 or mid[i] is None:
            upper.append(None)
            lower.append(None)
        else:
            sub = closes[i-n+1:i+1]
            mean = mid[i]
            std = np.std(sub)
            upper.append(mean + k * std)
            lower.append(mean - k * std)
    return upper, mid, lower

def calc_vwap(df, period=20):
    typical = (df['High'] + df['Low'] + df['Close']) / 3
    cum_pv = (typical * df['Volume']).rolling(period).sum()
    cum_vol = df['Volume'].rolling(period).sum()
    vwap = cum_pv / cum_vol
    return vwap

# ============================================================
# 主程式
# ============================================================
if query_btn or symbol_input:
    if not symbol_input:
        st.warning("請輸入股票代號")
        st.stop()

    # 格式化代號
    symbol = format_symbol(symbol_input, market)

    # 顯示查詢資訊
    st.info(f"📡 正在抓取 **{symbol}** 的數據...")

    try:
        # 抓取數據
        ticker = yf.Ticker(symbol)
        df_raw = ticker.history(period="1y", auto_adjust=True)

        if df_raw.empty:
            st.error(f"❌ 無法抓取 {symbol} 的數據，請檢查代號是否正確")
            st.stop()

        # 計算 MJ 指標
        df = calculate_mj_indicators(df_raw)
        if df is None:
            st.error("❌ 數據不足，需要至少 30 根 K 線")
            st.stop()

        # ============================================================
        # 週期選擇與數據準備
        # ============================================================
        period = st.radio(
            "📈 週期",
            options=["日線", "週線", "月線"],
            index=0,
            horizontal=True
        )

        if period == "日線":
            df_display = df.copy()
            period_label = "日線"
        elif period == "週線":
            df_display = resample_kline(df, rule='W-FRI')
            df_display = calculate_mj_indicators(df_display)
            period_label = "週線"
        else:
            df_display = resample_kline(df, rule='ME')
            df_display = calculate_mj_indicators(df_display)
            period_label = "月線"

        if df_display is None or len(df_display) < 30:
            st.warning(f"⚠️ {period_label} 數據不足，至少需要 30 根 K 線")
            st.stop()

        # 取最近 120 根，顯示 60 根
        df_show = df_display.tail(60).copy()
        dates = df_show.index.strftime('%Y-%m-%d').tolist()
        opens = df_show['Open'].tolist()
        highs = df_show['High'].tolist()
        lows = df_show['Low'].tolist()
        closes = df_show['Close'].tolist()
        volumes = df_show['Volume'].tolist()

        # ============================================================
        # 計算 MJ 標記（強中弱分級）
        # ============================================================
        j_vals = df_show['J'].tolist()
        hist_vals = df_show['Hist'].tolist()

        buy_signals = []
        sell_signals = []

        for i in range(2, len(j_vals) - 1):
            if j_vals[i] is None or j_vals[i-1] is None or hist_vals[i] is None or hist_vals[i-1] is None:
                continue

            # 買進：J穿50 + 柱狀體>0（今或明）
            j_cross_up = (j_vals[i-1] < 50 and j_vals[i] >= 50)
            h_pos_today = hist_vals[i] > 0
            h_pos_tomorrow = hist_vals[i+1] > 0 if i+1 < len(hist_vals) and hist_vals[i+1] is not None else False
            if j_cross_up and (h_pos_today or h_pos_tomorrow):
                buy_signals.append({
                    'date': dates[i],
                    'price': lows[i] * 0.97,
                    'strength': 1  # 預設弱
                })

            # 賣出：J破50 + 柱狀體<0（今或明）
            j_cross_down = (j_vals[i-1] > 50 and j_vals[i] <= 50)
            h_neg_today = hist_vals[i] < 0
            h_neg_tomorrow = hist_vals[i+1] < 0 if i+1 < len(hist_vals) and hist_vals[i+1] is not None else False
            if j_cross_down and (h_neg_today or h_neg_tomorrow):
                sell_signals.append({
                    'date': dates[i],
                    'price': highs[i] * 1.03,
                    'strength': 1
                })

        # ============================================================
        # 疊加指標選擇
        # ============================================================
        overlay = st.selectbox(
            "📊 疊加指標",
            options=["無", "MA", "布林", "VWAP"],
            index=0
        )

        # ============================================================
        # 繪圖（主圖 + 3個副圖）
        # ============================================================
        fig = make_subplots(
            rows=4, cols=1,
            shared_xaxes=True,
            vertical_spacing=0.05,
            row_heights=[0.4, 0.2, 0.2, 0.2],
            subplot_titles=(f"{symbol} - {period_label}", "成交量", "KDJ", "MACD")
        )

        # ---- 主圖：K線 ----
        fig.add_trace(go.Candlestick(
            x=dates,
            open=opens,
            high=highs,
            low=lows,
            close=closes,
            name='K線',
            increasing_line_color='#ef5350',
            decreasing_line_color='#26a69a'
        ), row=1, col=1)

        # ---- 主圖：MA ----
        if overlay == "MA":
            ma5 = calc_sma(closes, 5)
            ma20 = calc_sma(closes, 20)
            ma60 = calc_sma(closes, 60)
            fig.add_trace(go.Scatter(x=dates, y=ma5, mode='lines', name='MA5', line=dict(color='#ffb74d', width=1.2)), row=1, col=1)
            fig.add_trace(go.Scatter(x=dates, y=ma20, mode='lines', name='MA20', line=dict(color='#00e676', width=1.2)), row=1, col=1)
            fig.add_trace(go.Scatter(x=dates, y=ma60, mode='lines', name='MA60', line=dict(color='#f06292', width=1.2)), row=1, col=1)

        # ---- 主圖：布林 ----
        if overlay == "布林":
            upper, mid, lower = calc_bollinger(closes)
            fig.add_trace(go.Scatter(x=dates, y=upper, mode='lines', name='布林上', line=dict(color='#2962ff', width=1, dash='dot')), row=1, col=1)
            fig.add_trace(go.Scatter(x=dates, y=mid, mode='lines', name='布林中', line=dict(color='#2962ff', width=1, dash='dot')), row=1, col=1)
            fig.add_trace(go.Scatter(x=dates, y=lower, mode='lines', name='布林下', line=dict(color='#2962ff', width=1, dash='dot')), row=1, col=1)

        # ---- 主圖：VWAP ----
        if overlay == "VWAP":
            vwap = calc_vwap(df_show, 20)
            fig.add_trace(go.Scatter(x=dates, y=vwap, mode='lines', name='VWAP(20)', line=dict(color='#ff9800', width=1.5)), row=1, col=1)

        # ---- 主圖：MJ 買賣標記 ----
        if buy_signals:
            fig.add_trace(go.Scatter(
                x=[s['date'] for s in buy_signals],
                y=[s['price'] for s in buy_signals],
                mode='markers',
                marker=dict(symbol='triangle-up', size=10, color='#ef5350', line=dict(color='#ffffff', width=1)),
                name='買進',
                hoverinfo='text',
                text=[f"買進訊號<br>{s['date']}" for s in buy_signals]
            ), row=1, col=1)

        if sell_signals:
            fig.add_trace(go.Scatter(
                x=[s['date'] for s in sell_signals],
                y=[s['price'] for s in sell_signals],
                mode='markers',
                marker=dict(symbol='triangle-down', size=10, color='#26a69a', line=dict(color='#ffffff', width=1)),
                name='賣出',
                hoverinfo='text',
                text=[f"賣出訊號<br>{s['date']}" for s in sell_signals]
            ), row=1, col=1)

        # ---- 主圖：版面配置 ----
        fig.update_xaxes(gridcolor='#1f2937', tickfont=dict(color='#9ca3af'), row=1, col=1)
        fig.update_yaxes(gridcolor='#1f2937', tickfont=dict(color='#9ca3af'), side='right', row=1, col=1)

        # ---- 副圖 1：成交量 ----
        colors = ['#ef5350' if closes[i] >= closes[i-1] else '#26a69a' for i in range(len(closes))]
        fig.add_trace(go.Bar(x=dates, y=volumes, marker_color=colors, name='成交量'), row=2, col=1)
        fig.update_yaxes(title_text="張數", gridcolor='#1f2937', tickfont=dict(color='#9ca3af'), row=2, col=1)

        # ---- 副圖 2：KDJ ----
        k_vals = df_show['K'].tolist()
        d_vals = df_show['D'].tolist()
        fig.add_trace(go.Scatter(x=dates, y=k_vals, mode='lines', name='K', line=dict(color='#ffffff', width=1)), row=3, col=1)
        fig.add_trace(go.Scatter(x=dates, y=d_vals, mode='lines', name='D', line=dict(color='#ffeb3b', width=1)), row=3, col=1)
        fig.add_trace(go.Scatter(x=dates, y=j_vals, mode='lines', name='J', line=dict(color='#e91e63', width=1)), row=3, col=1)
        fig.update_yaxes(title_text="KDJ", gridcolor='#1f2937', tickfont=dict(color='#9ca3af'), row=3, col=1)

        # ---- 副圖 3：MACD ----
        dif_vals = df_show['DIF'].tolist()
        macd_signal_vals = df_show['MACD_Signal'].tolist()
        hist_colors = ['#ef5350' if h >= 0 else '#26a69a' for h in hist_vals if h is not None]
        fig.add_trace(go.Bar(x=dates, y=hist_vals, marker_color=hist_colors, name='柱狀體'), row=4, col=1)
        fig.add_trace(go.Scatter(x=dates, y=dif_vals, mode='lines', name='DIF', line=dict(color='#2196f3', width=1)), row=4, col=1)
        fig.add_trace(go.Scatter(x=dates, y=macd_signal_vals, mode='lines', name='Signal', line=dict(color='#ff9800', width=1)), row=4, col=1)
        fig.update_yaxes(title_text="MACD", gridcolor='#1f2937', tickfont=dict(color='#9ca3af'), row=4, col=1)

        # ---- 整體版面 ----
        fig.update_layout(
            template='plotly_dark',
            paper_bgcolor='#000000',
            plot_bgcolor='#000000',
            hovermode='closest',
            margin=dict(l=30, r=30, t=40, b=20),
            height=900,
            showlegend=False,
            xaxis=dict(showgrid=True, gridcolor='#1f2937'),
            yaxis=dict(showgrid=True, gridcolor='#1f2937'),
        )

        st.plotly_chart(fig, use_container_width=True)

        # ---- 統計資訊 ----
        col_stat1, col_stat2, col_stat3 = st.columns(3)
        with col_stat1:
            st.metric("📊 總 K 線數", len(df_show))
        with col_stat2:
            st.metric("🔺 買進訊號", len(buy_signals))
        with col_stat3:
            st.metric("🔻 賣出訊號", len(sell_signals))

    except Exception as e:
        st.error(f"❌ 發生錯誤：{str(e)}")
        st.info("💡 請檢查股票代號是否正確，或稍後再試")



# [Cell 臨時測試] 朋友版 MJ 看盤工具（直接在 Colab 執行）

import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from IPython.display import display
import datetime

print("📊 朋友版 MJ 看盤工具 (Colab 臨時版)")

# ============================================================
# 輸入設定（直接改這裡）
# ============================================================
SYMBOL = "2330.TW"      # ← 改成你想看的股票
PERIOD = "日線"         # 日線 / 週線 / 月線
OVERLAY = "無"          # 無 / MA / 布林 / VWAP
# ============================================================

# ============================================================
# MJ 指標計算
# ============================================================
def calculate_mj_indicators(df, j_period=21, fast=5, slow=34, signal=5):
    df = df.copy()
    if len(df) < 30:
        return None

    low_n = df['Low'].rolling(window=j_period).min()
    high_n = df['High'].rolling(window=j_period).max()
    denom = high_n - low_n
    denom = denom.replace(0, np.nan)
    rsv = (df['Close'] - low_n) / denom * 100
    rsv = rsv.fillna(50)

    k_list, d_list = [50.0], [50.0]
    for r in rsv.values[1:]:
        k = (2/3) * k_list[-1] + (1/3) * r
        d = (2/3) * d_list[-1] + (1/3) * k
        k_list.append(k)
        d_list.append(d)

    df['K'] = k_list
    df['D'] = d_list
    df['J'] = 3 * df['K'] - 2 * df['D']

    ema_fast = df['Close'].ewm(span=fast, adjust=False).mean()
    ema_slow = df['Close'].ewm(span=slow, adjust=False).mean()
    df['DIF'] = ema_fast - ema_slow
    df['MACD_Signal'] = df['DIF'].ewm(span=signal, adjust=False).mean()
    df['Hist'] = (df['DIF'] - df['MACD_Signal']) * 2

    return df

def resample_kline(df, rule='W-FRI'):
    resampled = df.resample(rule).agg({
        'Open': 'first', 'High': 'max', 'Low': 'min', 'Close': 'last', 'Volume': 'sum'
    }).dropna(subset=['Close'])
    return resampled

def calc_sma(data, window):
    if len(data) < window:
        return [None] * len(data)
    res = []
    for i in range(len(data)):
        if i < window - 1:
            res.append(None)
        else:
            res.append(sum(data[i-window+1:i+1]) / window)
    return res

def calc_bollinger(closes, n=20, k=2):
    mid = calc_sma(closes, n)
    upper, lower = [], []
    for i in range(len(closes)):
        if i < n - 1 or mid[i] is None:
            upper.append(None)
            lower.append(None)
        else:
            sub = closes[i-n+1:i+1]
            mean = mid[i]
            std = np.std(sub)
            upper.append(mean + k * std)
            lower.append(mean - k * std)
    return upper, mid, lower

def calc_vwap(df, period=20):
    typical = (df['High'] + df['Low'] + df['Close']) / 3
    cum_pv = (typical * df['Volume']).rolling(period).sum()
    cum_vol = df['Volume'].rolling(period).sum()
    return cum_pv / cum_vol

# ============================================================
# 抓取數據
# ============================================================
print(f"🔄 正在抓取 {SYMBOL} ...")

ticker = yf.Ticker(SYMBOL)
df_raw = ticker.history(period="1y", auto_adjust=True)

if df_raw.empty:
    print(f"❌ 無法抓取 {SYMBOL}")
else:
    print(f"✅ 抓取成功！共 {len(df_raw)} 筆")

    df = calculate_mj_indicators(df_raw)

    # 週期處理
    if PERIOD == "日線":
        df_display = df.copy()
    elif PERIOD == "週線":
        df_display = resample_kline(df, rule='W-FRI')
        df_display = calculate_mj_indicators(df_display)
    else:
        df_display = resample_kline(df, rule='ME')
        df_display = calculate_mj_indicators(df_display)

    df_show = df_display.tail(60).copy()
    dates = df_show.index.strftime('%Y-%m-%d').tolist()
    opens = df_show['Open'].tolist()
    highs = df_show['High'].tolist()
    lows = df_show['Low'].tolist()
    closes = df_show['Close'].tolist()
    volumes = df_show['Volume'].tolist()
    j_vals = df_show['J'].tolist()
    hist_vals = df_show['Hist'].tolist()

    # 找買賣訊號
    buy_signals = []
    sell_signals = []
    for i in range(2, len(j_vals) - 1):
        if j_vals[i] is None or j_vals[i-1] is None or hist_vals[i] is None or hist_vals[i-1] is None:
            continue
        j_cross_up = (j_vals[i-1] < 50 and j_vals[i] >= 50)
        h_pos_today = hist_vals[i] > 0
        h_pos_tomorrow = hist_vals[i+1] > 0 if i+1 < len(hist_vals) and hist_vals[i+1] is not None else False
        if j_cross_up and (h_pos_today or h_pos_tomorrow):
            buy_signals.append({'date': dates[i], 'price': lows[i] * 0.97})

        j_cross_down = (j_vals[i-1] > 50 and j_vals[i] <= 50)
        h_neg_today = hist_vals[i] < 0
        h_neg_tomorrow = hist_vals[i+1] < 0 if i+1 < len(hist_vals) and hist_vals[i+1] is not None else False
        if j_cross_down and (h_neg_today or h_neg_tomorrow):
            sell_signals.append({'date': dates[i], 'price': highs[i] * 1.03})

    # ============================================================
    # 繪圖
    # ============================================================
    fig = make_subplots(
        rows=4, cols=1,
        shared_xaxes=True,
        vertical_spacing=0.06,
        row_heights=[0.4, 0.2, 0.2, 0.2],
        subplot_titles=(f"{SYMBOL} - {PERIOD}", "成交量", "KDJ", "MACD")
    )

    # 主圖：K線
    fig.add_trace(go.Candlestick(
        x=dates, open=opens, high=highs, low=lows, close=closes,
        name='K線',
        increasing_line_color='#ef5350',
        decreasing_line_color='#26a69a'
    ), row=1, col=1)

    # 疊加指標
    if OVERLAY == "MA":
        fig.add_trace(go.Scatter(x=dates, y=calc_sma(closes, 5), mode='lines', name='MA5', line=dict(color='#ffb74d', width=1.2)), row=1, col=1)
        fig.add_trace(go.Scatter(x=dates, y=calc_sma(closes, 20), mode='lines', name='MA20', line=dict(color='#00e676', width=1.2)), row=1, col=1)
        fig.add_trace(go.Scatter(x=dates, y=calc_sma(closes, 60), mode='lines', name='MA60', line=dict(color='#f06292', width=1.2)), row=1, col=1)
    elif OVERLAY == "布林":
        upper, mid, lower = calc_bollinger(closes)
        fig.add_trace(go.Scatter(x=dates, y=upper, mode='lines', name='布林上', line=dict(color='#2962ff', width=1, dash='dot')), row=1, col=1)
        fig.add_trace(go.Scatter(x=dates, y=mid, mode='lines', name='布林中', line=dict(color='#2962ff', width=1, dash='dot')), row=1, col=1)
        fig.add_trace(go.Scatter(x=dates, y=lower, mode='lines', name='布林下', line=dict(color='#2962ff', width=1, dash='dot')), row=1, col=1)
    elif OVERLAY == "VWAP":
        vwap = calc_vwap(df_show, 20)
        fig.add_trace(go.Scatter(x=dates, y=vwap, mode='lines', name='VWAP(20)', line=dict(color='#ff9800', width=1.5)), row=1, col=1)

    # 買賣標記
    if buy_signals:
        fig.add_trace(go.Scatter(
            x=[s['date'] for s in buy_signals],
            y=[s['price'] for s in buy_signals],
            mode='markers',
            marker=dict(symbol='triangle-up', size=12, color='#ef5350', line=dict(color='#ffffff', width=1)),
            name='買進'
        ), row=1, col=1)

    if sell_signals:
        fig.add_trace(go.Scatter(
            x=[s['date'] for s in sell_signals],
            y=[s['price'] for s in sell_signals],
            mode='markers',
            marker=dict(symbol='triangle-down', size=12, color='#26a69a', line=dict(color='#ffffff', width=1)),
            name='賣出'
        ), row=1, col=1)

    # 副圖 1：成交量
    colors = ['#ef5350' if closes[i] >= closes[i-1] else '#26a69a' for i in range(len(closes))]
    fig.add_trace(go.Bar(x=dates, y=volumes, marker_color=colors, name='成交量'), row=2, col=1)

    # 副圖 2：KDJ
    fig.add_trace(go.Scatter(x=dates, y=df_show['K'], mode='lines', name='K', line=dict(color='#ffffff', width=1)), row=3, col=1)
    fig.add_trace(go.Scatter(x=dates, y=df_show['D'], mode='lines', name='D', line=dict(color='#ffeb3b', width=1)), row=3, col=1)
    fig.add_trace(go.Scatter(x=dates, y=df_show['J'], mode='lines', name='J', line=dict(color='#e91e63', width=1)), row=3, col=1)

    # 副圖 3：MACD
    hist_colors = ['#ef5350' if h >= 0 else '#26a69a' for h in hist_vals if h is not None]
    fig.add_trace(go.Bar(x=dates, y=hist_vals, marker_color=hist_colors, name='柱狀體'), row=4, col=1)
    fig.add_trace(go.Scatter(x=dates, y=df_show['DIF'], mode='lines', name='DIF', line=dict(color='#2196f3', width=1)), row=4, col=1)
    fig.add_trace(go.Scatter(x=dates, y=df_show['MACD_Signal'], mode='lines', name='Signal', line=dict(color='#ff9800', width=1)), row=4, col=1)

    # 版面設定
    fig.update_layout(
        template='plotly_dark',
        paper_bgcolor='#000000',
        plot_bgcolor='#000000',
        height=900,
        showlegend=False,
        margin=dict(l=20, r=20, t=50, b=20)
    )
    fig.update_xaxes(gridcolor='#1f2937', tickfont=dict(color='#9ca3af'))
    fig.update_yaxes(gridcolor='#1f2937', tickfont=dict(color='#9ca3af'))

    display(fig)

    print(f"\n📊 統計：總 K 線 {len(df_show)} 根 | 買進 {len(buy_signals)} 個 | 賣出 {len(sell_signals)} 個")
